//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Right Reserved.
        /// </summary>
        public static string AllRightReserved {
            get {
                return ResourceManager.GetString("AllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Belgelerimiz {
            get {
                return ResourceManager.GetString("Belgelerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Featured Products.
        /// </summary>
        public static string ExploreOneCikanUrunler {
            get {
                return ResourceManager.GetString("ExploreOneCikanUrunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief assistant of your household chores is small appliances, in other words Cecilo Technological Tinyers are always with you! Also, don&apos;t forget to take a look at our products in order to buy the most affordable small home appliances!.
        /// </summary>
        public static string FooterArticle {
            get {
                return ResourceManager.GetString("FooterArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string OneCikanUrunler {
            get {
                return ResourceManager.GetString("OneCikanUrunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PopularTags.
        /// </summary>
        public static string PopulerEtiketler {
            get {
                return ResourceManager.GetString("PopulerEtiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string PopulerUrunler {
            get {
                return ResourceManager.GetString("PopulerUrunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Popular Products.
        /// </summary>
        public static string PopulerUrunleriKesfet {
            get {
                return ResourceManager.GetString("PopulerUrunleriKesfet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string TumUrunlerimiz {
            get {
                return ResourceManager.GetString("TumUrunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Urunlerimiz {
            get {
                return ResourceManager.GetString("Urunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Products.
        /// </summary>
        public static string YeniGelenler {
            get {
                return ResourceManager.GetString("YeniGelenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our New Products.
        /// </summary>
        public static string YeniUrunler {
            get {
                return ResourceManager.GetString("YeniUrunler", resourceCulture);
            }
        }
    }
}
