//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Adres {
            get {
                return ResourceManager.GetString("Adres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Right Reserved.
        /// </summary>
        public static string AllRightReserved {
            get {
                return ResourceManager.GetString("AllRightReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Anasayfa {
            get {
                return ResourceManager.GetString("Anasayfa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Links.
        /// </summary>
        public static string Baglantilarimiz {
            get {
                return ResourceManager.GetString("Baglantilarimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The documents of our company are as follows..
        /// </summary>
        public static string BelgelerAlt {
            get {
                return ResourceManager.GetString("BelgelerAlt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        public static string Belgelerimiz {
            get {
                return ResourceManager.GetString("Belgelerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colors.
        /// </summary>
        public static string Colors {
            get {
                return ResourceManager.GetString("Colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EPOSTA {
            get {
                return ResourceManager.GetString("EPOSTA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EpostaContact {
            get {
                return ResourceManager.GetString("EpostaContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in the required fields!.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Etiketler {
            get {
                return ResourceManager.GetString("Etiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Featured Products.
        /// </summary>
        public static string ExploreOneCikanUrunler {
            get {
                return ResourceManager.GetString("ExploreOneCikanUrunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fast Links.
        /// </summary>
        public static string FastLinks {
            get {
                return ResourceManager.GetString("FastLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The chief assistant of your household chores is small appliances, in other words Cecilo Technological Tinyers are always with you! Also, don&apos;t forget to take a look at our products in order to buy the most affordable small home appliances!.
        /// </summary>
        public static string FooterArticle {
            get {
                return ResourceManager.GetString("FooterArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message has been sent successfully..
        /// </summary>
        public static string FormSuccess {
            get {
                return ResourceManager.GetString("FormSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing.
        /// </summary>
        public static string Gosteriliyor {
            get {
                return ResourceManager.GetString("Gosteriliyor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Iletisim {
            get {
                return ResourceManager.GetString("Iletisim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Kategoriler {
            get {
                return ResourceManager.GetString("Kategoriler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Konu {
            get {
                return ResourceManager.GetString("Konu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Surname.
        /// </summary>
        public static string NameSurname {
            get {
                return ResourceManager.GetString("NameSurname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Featured Products.
        /// </summary>
        public static string OneCikanUrunler {
            get {
                return ResourceManager.GetString("OneCikanUrunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string Paylas {
            get {
                return ResourceManager.GetString("Paylas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Tags.
        /// </summary>
        public static string PopulerEtiketler {
            get {
                return ResourceManager.GetString("PopulerEtiketler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popular Products.
        /// </summary>
        public static string PopulerUrunler {
            get {
                return ResourceManager.GetString("PopulerUrunler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore Popular Products.
        /// </summary>
        public static string PopulerUrunleriKesfet {
            get {
                return ResourceManager.GetString("PopulerUrunleriKesfet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string SendButton {
            get {
                return ResourceManager.GetString("SendButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WE ARE READY FOR YOUR QUESTIONS.
        /// </summary>
        public static string SorularinizIcin {
            get {
                return ResourceManager.GetString("SorularinizIcin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do You Have Any Questions.
        /// </summary>
        public static string SorunuzMuVar {
            get {
                return ResourceManager.GetString("SorunuzMuVar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOCIAL MEDIA.
        /// </summary>
        public static string SOSYALMEDYA {
            get {
                return ResourceManager.GetString("SOSYALMEDYA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TEL {
            get {
                return ResourceManager.GetString("TEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string TelefonContact {
            get {
                return ResourceManager.GetString("TelefonContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Toplam {
            get {
                return ResourceManager.GetString("Toplam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Products.
        /// </summary>
        public static string TumUrunlerimiz {
            get {
                return ResourceManager.GetString("TumUrunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Urun {
            get {
                return ResourceManager.GetString("Urun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Products.
        /// </summary>
        public static string Urunlerimiz {
            get {
                return ResourceManager.GetString("Urunlerimiz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Verify Code.
        /// </summary>
        public static string VerifyCode {
            get {
                return ResourceManager.GetString("VerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Products.
        /// </summary>
        public static string YeniGelenler {
            get {
                return ResourceManager.GetString("YeniGelenler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our New Products.
        /// </summary>
        public static string YeniUrunler {
            get {
                return ResourceManager.GetString("YeniUrunler", resourceCulture);
            }
        }
    }
}
